### ISSUE TITLE
Incorrect name for symbolic icons

### ISSUE THREAD

**Issue by sergio-costas** [ubuntu/gtk-common-themes#6]
I discovered that `share/icons/Adwaita/scalable/actions/sidebar-show-right-symbolic-rtl.svg` and `share/icons/Adwaita/scalable/actions/sidebar-show-symbolic-rtl.svg` have an incorrect name: they must have the "-symbolic" to the end, not the "-rtl".

**Comment by sergio-costas** [comment]
Here can be see: to the left is the list of icons in my Ubuntu 22.04 system; to the right, the list of icons in the /snap/gtk-common-themes folder.

![imagen](https://user-images.githubusercontent.com/105285003/176488226-49c2c242-6b9c-4816-9093-891180aad284.png)

**Comment by jhenstridge** [comment]
It looks like the name change was intentional:

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/3f63ef06344360dee9c382b79f3efc37b580915b

I don't think there is anything to fix here, and the latest candidate releases probably diverge even further from 22.04 (although it's not obvious if it is in ways that matter).
